apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-oozc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-oozc
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-oozc
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-oozc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-oozc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-depl-leaz-tenant/appstudio/dc-metro-map-oozc@sha256:82f873125862ef3300abea21ce4ba5f0c41651d0ecc1cd95f91c5bc439a65a5b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
